version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.3
